
framework:
  - terraform

compact: true

skip-check:

  - CKV_AWS_88   
  - CKV_AWS_2    # "Ensure ALB protocol is HTTPS" - Internal ALB, HTTPS terminates at CloudFront
  - CKV_AWS_103  # "Ensure ALB uses TLS 1.2" - Internal ALB uses HTTP, TLS at CloudFront edge
  - CKV_AWS_378  # "Ensure AWS Load Balancer doesn't use HTTP" - Internal ALB, encrypted at CloudFront
  - CKV2_AWS_20  # "Ensure ALB redirects HTTP to HTTPS" - Internal ALB, redirect handled by CloudFront
  - CKV_AWS_309  # "Ensure API Gateway routes specify authorization" - Public API for e-commerce catalog
  - CKV_AWS_305  # "Ensure CloudFront has default root object" - API proxy, no root object needed
  - CKV_AWS_310  # "Ensure CloudFront has origin failover" - Single origin architecture, acceptable
  - CKV2_AWS_47  # "Ensure WAF has Log4j rule" - Already using AWSManagedRulesKnownBadInputsRuleSet
  - CKV2_AWS_8   # "Ensure RDS has AWS Backup plan" - Using Aurora native backups with retention
  - CKV2_AWS_5   # "Ensure Security Groups are attached" - False positive, attached via VPC Link and ECS
  - CKV_AWS_130  # "Ensure VPC subnets don't assign public IP" - Public subnet needs IPs for internet access
  - CKV_AWS_18   # "Ensure S3 bucket has access logging" - Log buckets don't need recursive logging
  - CKV2_AWS_62  # "Ensure S3 has event notifications" - Not needed for log storage buckets
  - CKV2_AWS_65  # "Ensure S3 ACLs are disabled" - CloudFront logs require ACLs for writing
  - CKV2_AWS_61  # "Ensure S3 has lifecycle configuration" - False positive, lifecycle IS configured
  - CKV2_AWS_6   # "Ensure S3 has public access block" - False positive for count-based resources
  - CKV_AWS_21   # "Ensure S3 has versioning" - False positive for count-based resources
  - CKV2_AWS_31  # "Ensure WAF2 has logging" - False positive, logging IS configured
  - CKV2_AWS_32  # "Ensure CloudFront has response headers" - False positive, policy IS attached
